### PR TITLE
Fix AplRenderUtils, to use all parameters in APL document during APL preview

### PR DESCRIPTION
**Pull request by nikhilym**
## Description

APL 1.3 and above allows parameters to use key names other than `payload` as mentioned in the `About binding a data source to payload or other parameters` section [here](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-data-source.html#bind-the-data-source-to-the-document). When using a document that has custom named parameters, the APL previewer doesn't render the doc because it is only using the first parameter. This PR fixes that, by taking all parameters into consideration.

### APL Doc used (with multiple parameters)

*document.json*

```json
{
    "type": "APL",
    "version": "1.3",
    "settings": {},
    "theme": "dark",
    "import": [
        {
            "name": "alexa-layouts",
            "version": "1.1.0"
        }
    ],
    "resources": [],
    "styles": {
        "bigText": {
            "values": [
                {
                    "fontSize": "72dp",
                    "textAlign": "center"
                }
            ]
        }
    },
    "onMount": [],
    "graphics": {},
    "commands": {},
    "layouts": {},
    "mainTemplate": {
        "parameters": [
            "text",
            "assets"
        ],
        "items": [
            {
                "type": "Container",
                "when": "${@viewportProfile != @hubRoundSmall}",
                "items": [
                    {
                        "type": "Text",
                        "paddingTop": "12dp",
                        "paddingBottom": "12dp",
                        "text": "${text.start}",
                        "style": "bigText"
                    },
                    {
                        "type": "Text",
                        "text": "${text.middle}",
                        "style": "bigText"
                    },
                    {
                        "type": "Text",
                        "text": "${text.end}",
                        "style": "bigText"
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "AlexaImage",
                                "alignSelf": "center",
                                "imageSource": "${assets.cake}",
                                "imageRoundedCorner": false,
                                "imageScale": "best-fill",
                                "imageHeight": "40vh",
                                "imageAspectRatio": "square",
                                "imageBlurredBackground": false
                            }
                        ]
                    }
                ],
                "height": "100%",
                "width": "100%"
            },
            {
                "type": "Container",
                "when": "${@viewportProfile == @hubRoundSmall}",
                "items": [
                    {
                        "type": "Text",
                        "paddingTop": "75dp",
                        "text": "${text.start}",
                        "style": "bigText"
                    },
                    {
                        "type": "Text",
                        "text": "${text.middle}",
                        "style": "bigText"
                    },
                    {
                        "type": "Text",
                        "text": "${text.end}",
                        "style": "bigText"
                    }
                ],
                "height": "100%",
                "width": "100%"
            }
        ]
    }
}
```

*datasources/default.json*

```json
{
    "text": {
        "start": "Welcome",
        "middle": "to",
        "end": "Cake Time!"
    },
    "assets": {
        "cake": "https://github.com/alexa/skill-sample-nodejs-first-apl-skill/blob/master/modules/assets/alexaCake_960x960.png?raw=true"
    }
}
```

### Before change

Screen Shot 2020-11-24 at 1 59 29 PM

### After change

Screen Shot 2020-11-24 at 2 02 22 PM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by sattpat — APPROVED** [review]
Nice work on the fix!!

**Review by renewu0707 — COMMENTED** [review]
Do we also want to check if parsedData doesn't contains the name in parameters?

else {
  content.addData(name, '{}');
 }

**Comment by nikhilym** [comment]
@renewu0707 I tested the case where invalid parameters are used in `document.json` and the preview worked fine. However, I might be missing something. Do you think we need to still send in an empty `{}` to the `content` for missing names?

**Comment by renewu0707** [comment]
@nikhilym I am okay with keep the fix like this but just want to mention that the rest of places such as APL Authoring Tool has added this check. It maybe safer to avoid any other edge cases.

**Comment by nikhilym** [comment]
Totally agree. I will revert the commit and add the corresponding else condition, and send for re-approval.

**Pull request merged**
